num = int(input('Digite um número inteiro: '))
row = (num * 1)
row2 = (num * 2)
row3 = (num * 3)
row4 = (num * 4)
row5 = (num * 5)
row6 = (num * 6)
row7 = (num * 7)
row8 = (num * 8)
row9 = (num * 9)
row10 = (num * 10)

print('{} X  1 = {} \n{} X  2 = {} \n{} X  3 = {} \n{} X  4 = {} \n{} X  5 = {}'.format(num, row, num, row2, num, row3, num, row4, num, row5))
print('{} X  6 = {} \n{} X  7 = {} \n{} X  8 = {} \n{} X  9 = {} \n{} X 10 = {}'.format(num, row6, num, row7, num, row8, num, row9, num, row10))
